### ISSUE TITLE
connecting to Last.fm doesn't work

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#227]
When trying to connect to Last.fm, the page http://www.youtify.com/lastfm/connect gives me an error:

```
Traceback (most recent call last):
  File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 710, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/youtify/15.363074467270291314/lastfm.py", line 59, in get
    url = 'http://www.last.fm/api/auth/?api_key=db8b8dccb3afd186b6df786775a62cb5&cb=' + config.LASTFM_REDIRECT_URL
AttributeError: 'module' object has no attribute 'LASTFM_REDIRECT_URL'
```

**Comment by pthulin** [comment]
Btw Jan, this should be fixed now. Thanks for reporting.
