### ISSUE TITLE
Last.fm connect broken?

### ISSUE THREAD

**Issue by kallux** [youtify/youtify#233]
There are lots of error messages in the logs.

'module' object has no attribute 'LASTFM_REDIRECT_URL'
Traceback (most recent call last):
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in **call**
    rv = self.handle_exception(request, response, e)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in **call**
    rv = self.router.dispatch(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in **call**
    return handler.dispatch()
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(_args, *_kwargs)
  File "/base/data/home/apps/s~youtify-hrd/16.../lastfm.py", line 59, in get
    url = 'http://www.last.fm/api/auth/?api_key=<REPLACED>=' + config.LASTFM_REDIRECT_URL
AttributeError: 'module' object has no attribute 'LASTFM_REDIRECT_URL'

**Comment by arazalip** [comment]
It's ok on a local run. no problem with config on server?
