### ISSUE TITLE
/soundcloud_id_to_permalink stopped working.

### ISSUE THREAD

**Issue by kallux** [youtify/youtify#236]
No tracks from sound cloud can be played at the moment

'permalink_url'
Traceback (most recent call last):
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in **call**
    rv = self.handle_exception(request, response, e)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in **call**
    rv = self.router.dispatch(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in **call**
    return handler.dispatch()
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(_args, *_kwargs)
  File "/base/data/home/apps/s~youtify-hrd/16.368065972976853775/soundcloud_id_to_permalink.py", line 12, in get
    self.redirect(str(json['permalink_url']))
KeyError: 'permalink_url'

**Comment by kallux** [comment]
Seems to fixed. Probably a temporary issue.

**Comment by kallux** [comment]
Looks like we're hitting our request limit.
